/**
 @file ctc_interrupt.h

 @author  Copyright (C) 2011 Centec Networks Inc.  All rights reserved.

 @date 2010-1-20

 @version v2.0

   This file contains all isr related data structure, enum, macro and proto.
*/


 #ifndef _CTC_INTERRUPT_H
 #define _CTC_INTERRUPT_H
/****************************************************************
 *
 * Header Files
 *
 ***************************************************************/

/****************************************************************
*
* Defines and Macros
*
****************************************************************/

/**
 @defgroup isr ISR
 @{
*/


#define CTC_INTERRUPT_PARITY_ERROR_MAX_ENTRY_WORD     8

/**
 @brief Define interrupt type
*/
enum ctc_interrupt_intr_type_e
{
    CTC_INTERRUPT_NORMAL_INTR = 0,
    CTC_INTERRUPT_FATAL_INTR
};
typedef enum ctc_interrupt_intr_type_e ctc_interrupt_intr_type_t;

/**
 @brief Define normal interrupt type
*/
enum ctc_interrupt_normal_intr_type_e
{
    CTC_INTERRUPT_NORMAL_OAM_INTR = 12,               /**< normal OAM interrupt */
    CTC_INTERRUPT_NORMAL_STATISTICS_INTR = 14,        /**< normal statistics interrupt */
    CTC_INTERRUPT_NORMAL_LEARNING_INTR = 15,          /**< normal learning interrupt */
    CTC_INTERRUPT_NORMAL_AGING_INTR = 16,             /**< normal aging interrupt */
    CTC_INTERRUPT_NORMAL_PTP_INTR = 17,               /**< normal PTP interrupt */
    CTC_INTERRUPT_NORMAL_ALL = 18,                  /**< normal interrupt all */
    CTC_INTERRUPT_NORMAL_INTR_TYPE_MAX
};
typedef enum ctc_interrupt_normal_intr_type_e ctc_interrupt_normal_intr_type_t;

/**
 @brief Define fatal interrupt type
*/
enum ctc_interrupt_fatal_intr_type_e
{
    CTC_INTERRUPT_FATAL0_INTR = 0,

    CTC_INTERRUPT_FATAL0_MAC_MUX_INTR = 0,
    CTC_INTERRUPT_FATAL0_CPU_MAC_INTR,
    CTC_INTERRUPT_FATAL0_NET_TX_INTR,
    CTC_INTERRUPT_FATAL0_NET_RX_INTR,
    CTC_INTERRUPT_FATAL0_QUAD_MAC_APP0_INTR,
    CTC_INTERRUPT_FATAL0_QUAD_MAC_APP1_INTR,
    CTC_INTERRUPT_FATAL0_QUAD_MAC_APP2_INTR,
    CTC_INTERRUPT_FATAL0_QUAD_MAC_APP3_INTR,
    CTC_INTERRUPT_FATAL0_QUAD_MAC_APP4_INTR,
    CTC_INTERRUPT_FATAL0_QUAD_MAC_APP5_INTR,
    CTC_INTERRUPT_FATAL0_QUAD_MAC_APP6_INTR,
    CTC_INTERRUPT_FATAL0_QUAD_MAC_APP7_INTR,
    CTC_INTERRUPT_FATAL0_QUAD_MAC_APP8_INTR,
    CTC_INTERRUPT_FATAL0_QUAD_MAC_APP9_INTR,
    CTC_INTERRUPT_FATAL0_QUAD_MAC_APP10_INTR,
    CTC_INTERRUPT_FATAL0_QUAD_MAC_APP11_INTR,
    CTC_INTERRUPT_FATAL0_GMAC0_INTR,
    CTC_INTERRUPT_FATAL0_GMAC1_INTR,
    CTC_INTERRUPT_FATAL0_GMAC2_INTR,
    CTC_INTERRUPT_FATAL0_GMAC3_INTR,
    CTC_INTERRUPT_FATAL0_GMAC4_INTR,
    CTC_INTERRUPT_FATAL0_GMAC5_INTR,
    CTC_INTERRUPT_FATAL0_GMAC6_INTR,
    CTC_INTERRUPT_FATAL0_GMAC7_INTR,
    CTC_INTERRUPT_FATAL0_GMAC8_INTR,
    CTC_INTERRUPT_FATAL0_GMAC9_INTR,
    CTC_INTERRUPT_FATAL0_GMAC10_INTR,
    CTC_INTERRUPT_FATAL0_GMAC11_INTR,
    CTC_INTERRUPT_FATAL0_GMAC12_INTR,
    CTC_INTERRUPT_FATAL0_GMAC13_INTR,
    CTC_INTERRUPT_FATAL0_GMAC14_INTR,
    CTC_INTERRUPT_FATAL0_GMAC15_INTR,

    CTC_INTERRUPT_FATAL1_INTR = 32,

    CTC_INTERRUPT_FATAL1_GMAC16_INTR = 32,
    CTC_INTERRUPT_FATAL1_GMAC17_INTR,
    CTC_INTERRUPT_FATAL1_GMAC18_INTR,
    CTC_INTERRUPT_FATAL1_GMAC19_INTR,
    CTC_INTERRUPT_FATAL1_GMAC20_INTR,
    CTC_INTERRUPT_FATAL1_GMAC21_INTR,
    CTC_INTERRUPT_FATAL1_GMAC22_INTR,
    CTC_INTERRUPT_FATAL1_GMAC23_INTR,
    CTC_INTERRUPT_FATAL1_GMAC24_INTR,
    CTC_INTERRUPT_FATAL1_GMAC25_INTR,
    CTC_INTERRUPT_FATAL1_GMAC26_INTR,
    CTC_INTERRUPT_FATAL1_GMAC27_INTR,
    CTC_INTERRUPT_FATAL1_GMAC28_INTR,
    CTC_INTERRUPT_FATAL1_GMAC29_INTR,
    CTC_INTERRUPT_FATAL1_GMAC30_INTR,
    CTC_INTERRUPT_FATAL1_GMAC31_INTR,
    CTC_INTERRUPT_FATAL1_GMAC32_INTR,
    CTC_INTERRUPT_FATAL1_GMAC33_INTR,
    CTC_INTERRUPT_FATAL1_GMAC34_INTR,
    CTC_INTERRUPT_FATAL1_GMAC35_INTR,
    CTC_INTERRUPT_FATAL1_GMAC36_INTR,
    CTC_INTERRUPT_FATAL1_GMAC37_INTR,
    CTC_INTERRUPT_FATAL1_GMAC38_INTR,
    CTC_INTERRUPT_FATAL1_GMAC39_INTR,
    CTC_INTERRUPT_FATAL1_GMAC40_INTR,
    CTC_INTERRUPT_FATAL1_GMAC41_INTR,
    CTC_INTERRUPT_FATAL1_GMAC42_INTR,
    CTC_INTERRUPT_FATAL1_GMAC43_INTR,
    CTC_INTERRUPT_FATAL1_GMAC44_INTR,
    CTC_INTERRUPT_FATAL1_GMAC45_INTR,
    CTC_INTERRUPT_FATAL1_GMAC46_INTR,
    CTC_INTERRUPT_FATAL1_GMAC47_INTR,

    CTC_INTERRUPT_FATAL2_INTR = 64,

    CTC_INTERRUPT_FATAL2_EPE_STATS_INTR = 64,
    CTC_INTERRUPT_FATAL2_EPE_HDR_EDIT_INTR,
    CTC_INTERRUPT_FATAL2_EPE_CLASSIFICATION_INTR,
    CTC_INTERRUPT_FATAL2_EPE_ACLQOS_INTR,
    CTC_INTERRUPT_FATAL2_EPE_HDR_PROC_INTR,
    CTC_INTERRUPT_FATAL2_EPE_NEXTHOP_INTR,
    CTC_INTERRUPT_FATAL2_EPE_HDR_ADJ_INTR,
    CTC_INTERRUPT_FATAL2_EPE_PARSER_INTR,
    CTC_INTERRUPT_FATAL2_IPE_AGING_INTR,
    CTC_INTERRUPT_FATAL2_IPE_STATS_INTR,
    CTC_INTERRUPT_FATAL2_IPE_FWD_INTR,
    CTC_INTERRUPT_FATAL2_IPE_PKT_PROC_INTR,
    CTC_INTERRUPT_FATAL2_IPE_LKP_MGR_INTR,
    CTC_INTERRUPT_FATAL2_IPE_INTF_MAPPER_INTR,
    CTC_INTERRUPT_FATAL2_IPE_HDR_ADJ_INTR,
    CTC_INTERRUPT_FATAL2_IPE_PARSER_INTR,
    CTC_INTERRUPT_FATAL2_FABRIC_VOQ_INTR,
    CTC_INTERRUPT_FATAL2_FABRIC_SER_INTR,
    CTC_INTERRUPT_FATAL2_FABRIC_RXQ_INTR,
    CTC_INTERRUPT_FATAL2_FABRIC_RTS_INTR,
    CTC_INTERRUPT_FATAL2_FABRIC_GTS_INTR,
    CTC_INTERRUPT_FATAL2_FABRIC_DSF_INTR,
    CTC_INTERRUPT_FATAL2_FABRIC_CRB_INTR,
    CTC_INTERRUPT_FATAL2_FABRIC_CAS_INTR,
    CTC_INTERRUPT_FATAL2_SGMAC0_INTR,
    CTC_INTERRUPT_FATAL2_SGMAC1_INTR,
    CTC_INTERRUPT_FATAL2_SGMAC2_INTR,
    CTC_INTERRUPT_FATAL2_SGMAC3_INTR,
    CTC_INTERRUPT_FATAL2_XGMAC0_INTR,
    CTC_INTERRUPT_FATAL2_XGMAC1_INTR,
    CTC_INTERRUPT_FATAL2_XGMAC2_INTR,
    CTC_INTERRUPT_FATAL2_XGMAC3_INTR,

    CTC_INTERRUPT_FATAL3_INTR = 96,

    CTC_INTERRUPT_FATAL3_DS_HASH_KEY_TBL_INTR = 96,
    CTC_INTERRUPT_FATAL3_HASH_CTL_INTR,
    CTC_INTERRUPT_FATAL3_TCAM_CTL_EXT_INTR,
    CTC_INTERRUPT_FATAL3_TCAM_CTL_INT_INTR,
    CTC_INTERRUPT_FATAL3_PB_CTL_INTR,
    CTC_INTERRUPT_FATAL3_QDR_ARB_INTR,
    CTC_INTERRUPT_FATAL3_TB_INFO_ARB_INTR,
    CTC_INTERRUPT_FATAL3_TCAM_ARB_INTR,
    CTC_INTERRUPT_FATAL3_SHARED_DS_INTR,
    CTC_INTERRUPT_FATAL3_STP_STATE_INTR,
    CTC_INTERRUPT_FATAL3_STATISTICS_INTR,
    CTC_INTERRUPT_FATAL3_POLICING_INTR,
    CTC_INTERRUPT_FATAL3_MET_FIFO_INTR,
    CTC_INTERRUPT_FATAL3_ELOOP_INTR,
    CTC_INTERRUPT_FATAL3_BUF_RETRV_INTR,
    CTC_INTERRUPT_FATAL3_BUF_STORE_INTR,
    CTC_INTERRUPT_FATAL3_QMGR_QUE_ENTRY_INTR,
    CTC_INTERRUPT_FATAL3_QMGR_SUB_CH_INTR,
    CTC_INTERRUPT_FATAL3_QMGR_SCH_INTR,
    CTC_INTERRUPT_FATAL3_QMGR_LINKLIST_INTR,
    CTC_INTERRUPT_FATAL3_QMGR_ENQ_INTR,
    CTC_INTERRUPT_FATAL3_OAM_PROC_INTR,
    CTC_INTERRUPT_FATAL3_OAM_LKP_INTR,
    CTC_INTERRUPT_FATAL3_OAM_FWD_INTR,
    CTC_INTERRUPT_FATAL3_OAM_PARSER_INTR,
    CTC_INTERRUPT_FATAL3_QDR_CTL_INTR,
    CTC_INTERRUPT_FATAL3_DDR_CTL_INTR,

    CTC_INTERRUPT_FATAL_INTR_TYPE_MAX
};
typedef enum ctc_interrupt_fatal_intr_type_e ctc_interrupt_fatal_intr_type_t;


/**
 @brief Define fatal interrupt action
*/
enum ctc_interrupt_fatal_intr_action_e
{
    CTC_INTERRUPT_FATAL_INTR_NULL = 0,
    CTC_INTERRUPT_FATAL_INTR_LOG,
    CTC_INTERRUPT_FATAL_INTR_RESET,
    CTC_INTERRUPT_FATAL_INTR_RESET_MODULE
};
typedef enum ctc_interrupt_fatal_intr_action_e ctc_interrupt_fatal_intr_action_t;


/**
 @brief Define fatal interrupt status
*/
struct ctc_interrupt_fatal_intr_status_s
{
    uint32  sub_fatal_intr0;
    uint32  sub_fatal_intr1;
    uint32  sub_fatal_intr2;
    uint32  sub_fatal_intr3;
    ctc_interrupt_fatal_intr_action_t   action;
    uint8   is_parity_error_occur;
    uint8   parity_error_sram_type;         /**< 1: 16K sram; 2: 48K sram; 3: 96K sram; 4: 256K ext sram */
    uint8   rsv[2];
    uint32  parity_error_static_tbl_id;
    uint32  parity_error_index;             /**< The index of the table or the sram */
    uint32  parity_error_asic_addr;
    uint32  parity_error_asic_data[CTC_INTERRUPT_PARITY_ERROR_MAX_ENTRY_WORD];
    uint32  parity_error_mapping_addr;
    uint32  parity_error_mapping_data[CTC_INTERRUPT_PARITY_ERROR_MAX_ENTRY_WORD];
};
typedef struct ctc_interrupt_fatal_intr_status_s ctc_interrupt_fatal_intr_status_t;

/**@} end of @defgroup isr ISR  */

#endif

