BLD_DIR=$(SDK_DIR)/build.$(CPU).$(VER)
OBJ_DIR=$(BLD_DIR)/obj.$(BOARD)/core/humber
LIB_DIR=$(BLD_DIR)/lib.$(BOARD)
BIN_DIR=$(BLD_DIR)/bin.$(BOARD)

all_targets = src

all: $(all_targets) FORCE
clean: $(addprefix clean_,$(all_targets)) FORCE

src: FORCE
	make -C $(SDK_DIR)/core/humber/src -f Makefile.vx

clean_src: FORCE
	make -C $(SDK_DIR)/core/humber/src -f Makefile.vx clean

.PHONY: FORCE
FORCE:
