all_targets = src

all: $(all_targets) FORCE
clean: $(addprefix clean_,$(all_targets)) FORCE


src: FORCE
	make -C $(SDK_DIR)/driver/humber/src -f Makefile.vx

clean_src: FORCE
	make -C $(SDK_DIR)/driver/humber/src -f Makefile.vx  clean

.PHONY: FORCE
FORCE:
