BLD_DIR=$(SDK_DIR)/build.$(CPU).$(VER)
OBJ_DIR=$(BLD_DIR)/obj.$(BOARD)/core/api

all_targets = src

all: $(all_targets) FORCE
clean: $(addprefix clean_,$(all_targets)) FORCE

src: FORCE
	make -C $(SDK_DIR)/core/api/src -f Makefile.vx

clean_src: FORCE
	make -C $(SDK_DIR)/core/api/src -f Makefile.vx clean

.PHONY: FORCE
FORCE:
